# Generated by Django 5.1.4 on 2025-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220208_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_appropriate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reach_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
    ]
