# Generated by Django 5.1.4 on 2025-01-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0003_auto_20220213_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciepient',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='sent', max_length=10),
        ),
    ]
