# Generated by Django 5.1.4 on 2025-03-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0006_remove_message_file_remove_message_voice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
